# Generated by Django 6.0.3 on 2026-03-18 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceProvider_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=400)),
                ('password', models.CharField(max_length=300)),
                ('phoneno', models.CharField(max_length=300)),
                ('country', models.CharField(max_length=300)),
                ('state', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=300)),
                ('address', models.CharField(max_length=3000)),
                ('gender', models.CharField(max_length=300)),
            ],
        ),
    ]
