# Generated by Django 3.2.25 on 2026-03-18 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientRegister_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('password', models.CharField(max_length=10)),
                ('phoneno', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='detection_accuracy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=300)),
                ('ratio', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='detection_ratio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=300)),
                ('ratio', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='predict_cyber_attack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fid', models.CharField(max_length=300)),
                ('Timestamp', models.CharField(max_length=300)),
                ('Source_IP_Address', models.CharField(max_length=300)),
                ('Destination_IP_Address', models.CharField(max_length=300)),
                ('Source_Port', models.CharField(max_length=300)),
                ('Destination_Port', models.CharField(max_length=300)),
                ('Protocol', models.CharField(max_length=300)),
                ('Packet_Length', models.CharField(max_length=300)),
                ('Packet_Type', models.CharField(max_length=300)),
                ('Traffic_Type', models.CharField(max_length=300)),
                ('Alerts_Warnings', models.CharField(max_length=300)),
                ('Action_Taken', models.CharField(max_length=300)),
                ('Severity_Level', models.CharField(max_length=300)),
                ('Device_Information', models.CharField(max_length=300)),
                ('Network_Segment', models.CharField(max_length=300)),
                ('Geolocation_Data', models.CharField(max_length=300)),
                ('ProxyInformation', models.CharField(max_length=300)),
                ('FirewallLogs', models.CharField(max_length=300)),
                ('IDS_IPS_Alerts', models.CharField(max_length=300)),
                ('Log_Source', models.CharField(max_length=300)),
                ('Prediction', models.CharField(max_length=300)),
            ],
        ),
    ]
